name: TokensEconomy
version: '${project.version}'
main: net.noscape.project.tokenseco.TokensEconomy
api-version: 1.13
authors: [NoScape]
description: New tokens economy for buying/trading!
softdepend: [PlaceholderAPI, Vault]

commands:
  tokens:
    aliases: [token, te]
  tadmin:
    description: tadmin main command.
  exchange:
  balance:
    aliases: [balance, tokens]
  baltop:
    aliases: [topbal]
  pay:
    aliases: [give]
  toggle:
    aliases: [toggletoken]
  bank:
    description: bank system command
